# Generated by Django 4.1 on 2024-05-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabin",
            fields=[
                ("cabin_id", models.AutoField(primary_key=True, serialize=False)),
                ("cabin_name", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["course", "cabin_name", "session"],
            },
        ),
        migrations.CreateModel(
            name="Camper",
            fields=[
                ("camper_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "disambiguator"],
            },
        ),
        migrations.CreateModel(
            name="Counselor",
            fields=[
                ("counselor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "disambiguator"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_number", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["course_number", "course_name"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                ("period_id", models.AutoField(primary_key=True, serialize=False)),
                ("period_sequence", models.IntegerField(unique=True)),
                ("period_name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "ordering": ["period_sequence"],
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                ("year_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session",
                        to="courseinfo.period",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session",
                        to="courseinfo.year",
                    ),
                ),
            ],
            options={
                "ordering": ["year__year", "period__period_sequence"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "registration_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "cabin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="courseinfo.cabin",
                    ),
                ),
                (
                    "camper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="courseinfo.camper",
                    ),
                ),
            ],
            options={
                "ordering": ["cabin", "camper"],
            },
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("course_number", "course_name"), name="unique_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="counselor",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_counselor",
            ),
        ),
        migrations.AddConstraint(
            model_name="camper",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_camper",
            ),
        ),
        migrations.AddField(
            model_name="cabin",
            name="counselor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cabins",
                to="courseinfo.counselor",
            ),
        ),
        migrations.AddField(
            model_name="cabin",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cabins",
                to="courseinfo.course",
            ),
        ),
        migrations.AddField(
            model_name="cabin",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cabins",
                to="courseinfo.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("year", "period"), name="unique_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("cabin", "camper"), name="unique_registration"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("cabin", "camper")},
        ),
        migrations.AddConstraint(
            model_name="cabin",
            constraint=models.UniqueConstraint(
                fields=("session", "course", "cabin_name"), name="unique_cabin"
            ),
        ),
    ]
